blank_issues_enabled: false
contact_links:
  - name: Вопросы и обсуждения
    url: https://github.com/ivan8597/hr-analityc/discussions
    about: Пожалуйста, используйте Discussions для общих вопросов