name: ✨ Feature Request
description: Предложите новую функцию
title: '[Feature]: '
labels: ['feature', 'enhancement']
body:
  - type: textarea
    id: problem
    attributes:
      label: Какая проблема или потребность?
      description: Для кого это нужно?
  - type: textarea
    id: solution
    attributes:
      label: Предлагаемое решение
  - type: textarea
    id: alternatives
    attributes:
      label: Альтернативные варианты